using System;
using System.IO;
using System.IO.Compression;

namespace SurvivorFoundation.Tests
{
    /// <summary>Captured by an isolated process loading the pre-change 97a2b34 Survivor DLL.
    /// Baseline Runtime/*.cs and Systems/SvSystems.cs were compared byte-for-byte against git 97a2b34.
    /// This is a fixed old-build fixture, never generated by the code under test.</summary>
    static class SvLegacySnapshotFixtures
    {
        // Raw checkpoint SHA-256: d9951f51cbe8279916a493867b53dce6f1eee24b2becfec51cc59fc9ebb6e0c6
        public const string Checkpoint = "H4sIAAAAAAACA+2aPW8TQRCG5w4DDh8icQUShQtEAZIboIzv4piYAiEjK4lEd+RWwcLOWeczyF1+ARGlg4So7YaGDiVWCpTC1IgCUUBLSZEKdrx7d+sjVNCA3kd6pZ252Z3Z8VbWFIjoxpQvTqO+sm5Ju0aKE1L5xpPS7S3R7s9rh81OHWAZSv3bLtHYvTp6N74ZPHOz/pfXD8cPujtT/xW9d3cwKFMS06kopXDs4pkP5d3BR0cul4hea6XMyUIrvVZLRK6u1DIqNatNPhQWFqbHsX1ZpWeb3k/ulrmUz5++8Vn0Q3JKHl8T7eIxXchWaiUrFTF21b1eTRX7baPJTEf7WLlMX23j9JxxG9J2feleIx+KzWY3CvuF9SBs+aWqkEbQv98TPWFWmNfxx4Sd5jt6bWGtrb5x1lZv7Y+GQ2c0vLZfOvKd0tHXPaLDilKan3kxuORcVEvZwO09+ku8nUwWTfv5wXcn+SVtfZG46nPxS62FTZ/IPTB1Uncq7iS/JvNd5Iws/NKtuVkfAAAAAAAAAAAAAADg38D6T2VDEARBEARBEARBEPRH4pmgeKKNZ4fU9JOaaIun18zprBjex0NKM8NJPLF0pxl1s39KzCdW0Y1X8YQTx/OIW1V40aMu/SZNGnEhGYdrdLynW7/sKOod2bjznEuEQdVre5siW6G6Xt3lnbORfMHlQJ6zEQk/myxndCEJOiuNFSH8h97GY/5o2kQ/ARfoOn2YKAAA";
        // Raw continuation SHA-256: 879e44cd7459e1229dc5f9303453780923a929316262b2f52954c58826b9dc32
        public const string Continued = "H4sIAAAAAAACA+2aP4sTQRjG341RE//gn8pC4Qobr8g3MJmL8WIhemFZzna9Hc9gchv3Nkq69H6CXCWITQT1C3iJViInVodY2Ii1gmBxcBDnzc4kk/VSaSH4/OCBed99Z+ad2SmfS0T05TPzs+SuLK86Kq5SwiGlnPugcHVDNjundSLDSV3gWJrmu4JoKPI7T4avLoQinV90nw7fnbk/zl/Uc7d6vSJNau6UiVplsuDay8c+Frd6n0pquET0UmtKXjVabjcaMha6U8fq1O528uFZvz9ejuPzyfYc0/ud60Vu5Za3y2vRSHFELV+VzYUDbiHdqTMZJRVDkZzr8Vgmn7EumWnpHCubuteMtXrWOg3peGXphpuL5Hp9M446Z1fDqBEUKlIFYafWlm1pd5jT9QeUHeUz+k3p1DxP1Lzdwf7optgffRgU9oJSYe/rNnVfq//ytmzvz3z/9rx0LhmqC+xu01/iRX9xYMfej0fCjPkMpuET5pFWo3pAJN7YOqwvyVwiPyT7SWStDfiRO/nZHAAAAAAAAAAAAAAA/xMO9M8pA0EQBEEQBEEQBEHQH4k9QcbMxt6hxPiUmNmMcc02Zhl4HpuUZsxJ7Fi6Vo83aU6x+c5utor047tzK6cVpybON7flP9z4bcaCnpGuO8l7ySis+E1/XaZnGV/ZbBUf5kqo1liLZTBvykzRcRUsSxnc9tfu8Uc7JvoF3bmbeX8oAAA=";
        public static byte[] Decode(string encoded)
        {
            using var input = new MemoryStream(Convert.FromBase64String(encoded));
            using var gzip = new GZipStream(input, CompressionMode.Decompress);
            using var output = new MemoryStream();
            gzip.CopyTo(output);
            return output.ToArray();
        }
    }
}
